#!/bin/sh

# User startup script

# Uncomment the following and set a proper <DNS_IP> if your
# network configuration is static.
# echo "nameserver <DNS_IP>" > /tmp/resolv.conf

# Load the RP architecture driver
insmod /opt/bin/rpad.ko

echo "Feel free to add custom initialization commands here."
